routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', [
    'uses' => 'HomeController@index',
    'as' => 'home'
]);

Auth::routes();


// PaymentType
Route::group( ['prefix' => 'paymentType', 'middleware' => ['role:super_admin|admin']], function () {
    Route::get('/',                                            ['as'=>'paymentTypes.index',   'uses'=>'PaymentTypeController@index']);
    Route::get('/create',                                      ['as'=>'paymentTypes.create',  'uses'=>'PaymentTypeController@create']);
    Route::post('/',                                           ['as'=>'paymentTypes.store',   'uses'=>'PaymentTypeController@store']);
    Route::get('/{paymentType_id}',                            ['as'=>'paymentTypes.show',    'uses'=>'PaymentTypeController@show']);
    Route::match(['put', 'patch'], '/{paymentType_id}',        ['as'=>'paymentTypes.update',  'uses'=>'PaymentTypeController@update']);
    Route::delete('/{paymentType_id}',                         ['as'=>'paymentTypes.destroy', 'uses'=>'PaymentTypeController@destroy']);
    Route::get('/{paymentType_id}/edit',                       ['as'=>'paymentTypes.edit',    'uses'=>'PaymentTypeController@edit']);
});

// Payments
Route::group( ['prefix' => 'payments', 'middleware' => ['role:super_admin|admin|seller']], function () {
    Route::get('/',                                         ['as'=>'payments.index',   'uses'=>'PaymentController@index']);
    Route::get('/create',                                   ['as'=>'payments.create',  'uses'=>'PaymentController@create']);
    Route::post('/',                                        ['as'=>'payments.store',   'uses'=>'PaymentController@store']);
    Route::get('/{payment_id}',                             ['as'=>'payments.show',    'uses'=>'PaymentController@show']);
    Route::match(['put', 'patch'], '/{payment_id}',         ['as'=>'payments.update',  'uses'=>'PaymentController@update']);
    Route::delete('/{payment_id}',                          ['as'=>'payments.destroy', 'uses'=>'PaymentController@destroy']);
    Route::get('/{payment_id}/edit',                        ['as'=>'payments.edit',    'uses'=>'PaymentController@edit']);
});

// SellProducts
Route::group( ['prefix' => 'sellProducts', 'middleware' => ['role:super_admin|admin|seller']], function () {
    Route::get('/',                                         ['as'=>'sellProducts.index',   'uses'=>'SellProductController@index']);
    Route::get('/create',                                   ['as'=>'sellProducts.create',  'uses'=>'SellProductController@create']);
    Route::post('/',                                        ['as'=>'sellProducts.store',   'uses'=>'SellProductController@store']);
    Route::get('/{sellProduct_id}',                         ['as'=>'sellProducts.show',    'uses'=>'SellProductController@show']);
    Route::match(['put', 'patch'], '/{sellProduct_id}',     ['as'=>'sellProducts.update',  'uses'=>'SellProductController@update']);
    Route::delete('/{sellProduct_id}',                      ['as'=>'sellProducts.destroy', 'uses'=>'SellProductController@destroy']);
    Route::get('/{sellProduct_id}/edit',                    ['as'=>'sellProducts.edit',    'uses'=>'SellProductController@edit']);
});

// Sells
Route::group( ['prefix' => 'sells', 'middleware' => ['role:super_admin|admin|seller']], function () {
    Route::get('/',                                         ['as'=>'sells.index',       'uses'=>'SellController@index']);
    Route::get('/create',                                   ['as'=>'sells.create',      'uses'=>'SellController@create']);
    Route::post('/',                                        ['as'=>'sells.store',       'uses'=>'SellController@store']);
    Route::get('/{sell_id}',                                ['as'=>'sells.show',        'uses'=>'SellController@show']);
    Route::match(['put', 'patch'], '/{sell_id}',            ['as'=>'sells.update',      'uses'=>'SellController@update']);
    Route::delete('/{sell_id}',                             ['as'=>'sells.destroy',     'uses'=>'SellController@destroy']);
    Route::get('/{sell_id}/edit',                           ['as'=>'sells.edit',        'uses'=>'SellController@edit']);
    Route::get('/getProduct/{product_id}',                  ['as'=>'sells.getProduct',  'uses'=>'SellController@getProductById']);

});

// Customers
Route::group( ['prefix' => 'customers', 'middleware' => ['role:super_admin|admin|seller']], function () {
    Route::get('/',                                         ['as'=>'customers.index',   'uses'=>'CustomerController@index']);
    Route::get('/create',                                   ['as'=>'customers.create',  'uses'=>'CustomerController@create']);
    Route::post('/',                                        ['as'=>'customers.store',   'uses'=>'CustomerController@store']);
    Route::get('/{customer_id}',                            ['as'=>'customers.show',    'uses'=>'CustomerController@show']);
    Route::match(['put', 'patch'], '/{customer_id}',        ['as'=>'customers.update',  'uses'=>'CustomerController@update']);
    Route::delete('/{customer_id}',                         ['as'=>'customers.destroy', 'uses'=>'CustomerController@destroy']);
    Route::get('/{customer_id}/edit',                       ['as'=>'customers.edit',    'uses'=>'CustomerController@edit']);
});

// Shops
Route::group( ['prefix' => 'shops', 'middleware' => ['role:super_admin']], function () {
    Route::get('/',                                         ['as'=>'shops.index',   'uses'=>'ShopController@index']);
    Route::get('/create',                                   ['as'=>'shops.create',  'uses'=>'ShopController@create']);
    Route::post('/',                                        ['as'=>'shops.store',   'uses'=>'ShopController@store']);
    Route::get('/{shop_id}',                                ['as'=>'shops.show',    'uses'=>'ShopController@show']);
    Route::match(['put', 'patch'], '/{shop_id}',            ['as'=>'shops.update',  'uses'=>'ShopController@update']);
    Route::delete('/{shop_id}',                             ['as'=>'shops.destroy', 'uses'=>'ShopController@destroy']);
    Route::get('/{shop_id}/edit',                           ['as'=>'shops.edit',    'uses'=>'ShopController@edit']);
});

// Products
Route::group(['prefix' => 'products',  'middleware' => ['role:super_admin|admin']], function () {
    Route::get('/',                                         ['as'=>'products.index',   'uses'=>'ProductController@index']);
    Route::get('/create',                                   ['as'=>'products.create',  'uses'=>'ProductController@create']);
    Route::post('/',                                        ['as'=>'products.store',   'uses'=>'ProductController@store']);
    Route::get('/{product_id}',                             ['as'=>'products.show',    'uses'=>'ProductController@show']);
    Route::match(['put', 'patch'], '/{product_id}',         ['as'=>'products.update',  'uses'=>'ProductController@update']);
    Route::delete('/{product_id}',                          ['as'=>'products.destroy', 'uses'=>'ProductController@destroy']);
    Route::get('/{product_id}/edit',                        ['as'=>'products.edit',    'uses'=>'ProductController@edit']);
});

// Users
Route::group(['prefix' => 'users', 'middleware' => ['role:super_admin|admin']], function () {
    Route::get('/',                                         ['as'=>'users.index',   'uses'=>'UserController@index']);
    Route::get('/create',                                   ['as'=>'users.create',  'uses'=>'UserController@create']);
    Route::post('/',                                        ['as'=>'users.store',   'uses'=>'UserController@store']);
    Route::get('/{user_id}',                                ['as'=>'users.show',    'uses'=>'UserController@show']);
    Route::match(['put', 'patch'], '/{user_id}',            ['as'=>'users.update',  'uses'=>'UserController@update']);
    Route::delete('/{user_id}',                             ['as'=>'users.destroy', 'uses'=>'UserController@destroy']);
    Route::get('/{user_id}/edit',                           ['as'=>'users.edit',    'uses'=>'UserController@edit']);
});

Route::resource('categories', 'CategoryController');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>InfyOm Generator</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Theme style -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.3/css/AdminLTE.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.3/css/skins/_all-skins.min.css">

    <!-- iCheck -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/skins/square/_all.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/css/select2.min.css">

    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/css/bootstrap-datetimepicker.min.css">

    @yield('css')
</head>

<body class="skin-blue sidebar-mini">
@if (!Auth::guest())
    <div class="wrapper">
        <!-- Main Header -->
        <header class="main-header">

            <!-- Logo -->
            <a href="#" class="logo">
                <b>InfyOm</b>
            </a>

            <!-- Header Navbar -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- User Account Menu -->
                        <li class="dropdown user user-menu">
                            <!-- Menu Toggle Button -->
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <!-- The user image in the navbar-->
                                <img src="http://infyom.com/images/logo/blue_logo_150x150.jpg"
                                     class="user-image" alt="User Image"/>
                                <!-- hidden-xs hides the username on small devices so only the image appears. -->
                                <span class="hidden-xs">{!! Auth::user()->name !!}</span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- The user image in the menu -->
                                <li class="user-header">
                                    <img src="http://infyom.com/images/logo/blue_logo_150x150.jpg"
                                         class="img-circle" alt="User Image"/>
                                    
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="#" class="btn btn-default btn-flat">Profile</a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="{!! url('/logout') !!}" class="btn btn-default btn-flat"
                                            onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                            Sign out
                                        </a>
                                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>

        <!-- Left side column. contains the logo and sidebar -->
        @include('layouts.sidebar')
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            @yield('content')
        </div>

        <!-- Main Footer -->
        <footer class="main-footer" style="max-height: 100px;text-align: center">
            <strong>Copyright © 2016 <a href="#">Company</a>.</strong> All rights reserved.
        </footer>

    </div>
@else
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{!! url('/') !!}">
                    InfyOm Generator
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    <li><a href="{!! url('/home') !!}">Home</a></li>
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    <li><a href="{!! url('/login') !!}">Login</a></li>
                    <li><a href="{!! url('/register') !!}">Register</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div id="page-content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    @yield('content')
                </div>
            </div>
        </div>
    </div>
    @endif

    <!-- jQuery 3.1.1 -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.1/moment.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.3/js/adminlte.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/icheck.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/js/select2.min.js"></script>

    @yield('scripts')
    @stack('scripts')
</body>
</html>

resources/views/layouts/datatables_css.blade.php
<!-- DataTable Bootstrap -->
<link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.3.1/css/buttons.bootstrap.min.css">

resources/views/layouts/datatables_js.blade.php
<!-- Datatables -->
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/buttons.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/buttons.colVis.min.js"></script>
<script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>

resources/views/layouts/menu.blade.php
@role('admin')
<li class="{{ Request::is('home*') ? 'active' : '' }}">
    <a href="{{ route('home') }}"><i class="fa fa-info-circle"></i><span>Dashboard</span></a>
</li>
@endrole

@role('super_admin')
<li class="{{ Request::is('shops*') ? 'active' : '' }}">
    <a href="{{ route('shops.index') }}"><i class="fa fa-building"></i><span>Shops</span></a>
</li>
@endrole

@hasanyrole('super_admin|admin')
<li class="{{ Request::is('users*') ? 'active' : '' }}">
    <a href="{{ route('users.index') }}"><i class="fa fa-users"></i><span>Usuários</span></a>
</li>
@endhasanyrole

<li class="{{ Request::is('customers*') ? 'active' : '' }}">
    <a href="{{ route('customers.index') }}"><i class="fa fa-user-circle"></i><span>Clientes</span></a>
</li>

@hasanyrole('super_admin|admin')
<li class="{{ Request::is('categories*') ? 'active' : '' }}">
    <a href="{{ route('categories.index') }}"><i class="fa fa-list"></i><span>Categorias</span></a>
</li>

<li class="{{ Request::is('products*') ? 'active' : '' }}">
    <a href="{{ route('products.index') }}"><i class="fa fa-product-hunt"></i><span>Produtos</span></a>
</li>
@endhasanyrole

<li class="{{ Request::is('sells*') ? 'active' : '' }}">
    <a href="{{ route('sells.index') }}"><i class="fa fa-clipboard"></i><span>Vendas</span></a>
</li>

<li class="{{ Request::is('payments*') ? 'active' : '' }}">
    <a href="{{ route('payments.index') }}"><i class="fa fa-money"></i><span>Pagamentos</span></a>
</li>

resources/views/layouts/sidebar.blade.php
<aside class="main-sidebar" id="sidebar-wrapper">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- Sidebar user panel (optional) -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="http://infyom.com/images/logo/blue_logo_150x150.jpg" class="img-circle"
                     alt="User Image"/>
            </div>
            <div class="pull-left info">
                @if (Auth::guest())
                <p>InfyOm</p>
                @else
                    <p>{{ Auth::user()->name}}</p>
                @endif
                <!-- Status -->
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>

        <!-- search form (Optional) -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search..."/>
          <span class="input-group-btn">
            <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i>
            </button>
          </span>
            </div>
        </form>
        <!-- Sidebar Menu -->

        <ul class="sidebar-menu" data-widget="tree">
            @include('layouts.menu')
        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>